# Generated by Django 4.2.1 on 2023-06-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_streaming_backend', '0004_remove_song_liked_song_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='likes',
            new_name='liked',
        ),
    ]
